### PR TITLE
ci: add advanced cargo checks including fmt, clippy, and audit

### PR DESCRIPTION
**Pull request by antonbaliasnikov**
# What ❔

Add advanced cargo checks: fmt, clippy, udeps (unused dependencies), audit

## Checklist

- [x] PR title corresponds to the body of PR.
- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] Code has been formatted via `cargo fmt` and checked with `cargo clippy`.

### CODE REVIEW

**Comment by antonbaliasnikov** [comment]
@hedgar2017 , could you, please, also remove `TruffleHog` from mandatory checks for this repo?

**Review by hedgar2017 — APPROVED** [review]

**Comment by hedgar2017** [comment]
> @hedgar2017 , could you, please, also remove `TruffleHog` from mandatory checks for this repo?

It was added by Devops/Infosec.
Could you outline why we should remove it?

**Comment by hedgar2017** [comment]
> @hedgar2017 , could you, please, also remove `TruffleHog` from mandatory checks for this repo?

It's quite useful to find unwanted stuff in commited code.
It's probably just broken and we should check out why.

**Comment by antonbaliasnikov** [comment]
> > @hedgar2017 , could you, please, also remove `TruffleHog` from mandatory checks for this repo?
> 
> It's quite useful to find unwanted stuff in commited code. It's probably just broken and we should check out why.

We still have this check, but the repository requirement is not properly configured requiring it to be a _job_. I explained it in the other PR some time ago, can't find it. It can set it up, but with admin permissions only.

**Pull request merged**
